list1 = []
Studen1 = input("Enter the Marks of Student number 1 : ")
list1.append(Studen1)
Studen2 = input("Enter the Marks of Student number 2 : ")
list1.append(Studen2)
Studen3 = input("Enter the Marks of Student number 3 : ")
list1.append(Studen3)
Studen4 = input("Enter the Marks of Student number 4 : ")
list1.append(Studen4)
Studen5 = input("Enter the Marks of Student number 5 : ")
list1.append(Studen5)
Studen6 = input("Enter the Marks of Student number 6 : ")
list1.append(Studen6)
Studen7 = input("Enter the Marks of Student number 7 : ")
list1.append(Studen7)
list1.sort()
print(list1)