list1 = []
Fruit1 = input("Enter the Fruit number 1 : ")
list1.append(Fruit1)
Fruit2 = input("Enter the Fruit number 2 : ")
list1.append(Fruit2)
Fruit3 = input("Enter the Fruit number 3 : ")
list1.append(Fruit3)
Fruit4 = input("Enter the Fruit number 4 : ")
list1.append(Fruit4)
Fruit5 = input("Enter the Fruit number 5 : ")
list1.append(Fruit5)
Fruit6 = input("Enter the Fruit number 6 : ")
list1.append(Fruit6)
Fruit7 = input("Enter the Fruit number 7 : ")
list1.append(Fruit7)
print(list1)